version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
      - export PATH=~/.guard/bin:$PATH
      - cfn-guard --version
  build:
    commands:
      - echo Validating all templates in ./template directory...
      - |
        set -ueo pipefail
        files=$(find template/ -type f \( -name "*.yml" -o -name "*.yaml" \))
        for file in $files; do
          echo "Validating $file"
          aws cloudformation validate-template --template-body "file://$file"
          echo "Running cfn-guard ruleset on $file"
          cfn-guard validate --rules ${CICD_WORK_DIR}/${CFN_RULESET_FILE} --data $file --show-summary all
        done
      # - echo Packaging main template...
      # - |
      #   aws cloudformation package \
      #     --template-file template/main.yml \
      #     --s3-bucket $TEMPLATE_BUCKET \
      #     --output-template-file packaged-template.yml
artifacts:
  files:
    # - packaged-template.yml
    - ${CICD_WORK_DIR}/$PARAMETER_FILE
    - template/**
